### PR TITLE
Added function to return module slot properties

### PR DESCRIPTION
**Pull request by bbbowden**
I added a function that returns the module properties at a slot location.  This allows for the top level code to know the capabilities of each of the connected modules.  This allows me to use a generic code base for the P1AM and add or remove modules without having to change the code.

### CODE REVIEW

**Comment by AdamCummick** [comment]
@bbbowden Thank you for the contribution, this looks great. Would you mind adding an example that can demo the concept of using a generic code base?

**Comment by bbbowden** [comment]
`uint8_t digitalInputBytes = 0;
uint8_t digitalOutputBytes = 0;
uint8_t numberOfSlices = 0;

void setup()
{

Serial.begin(115200);
    while (!Serial) {}// wait for serial port to connect.

numberOfSlices = P1.init();

for (uint8_t slotIndex = 0; slotIndex < numberOfSlices; slotIndex++) {
        moduleProps slotProps = P1.readSlotProps(slotIndex);

        digitalInputBytes += (uint8_t)slotProps.diBytes;
        digitalOutputBytes += (uint8_t)slotProps.doBytes;
    }

    Serial.print("Digital Input Bytes: "); Serial.println(digitalInputBytes);
    Serial.print("Digital Output Bytes: "); Serial.println(digitalOutputBytes);

}

void loop()
{
    //Nothing to do.
}
`

**Comment by bbbowden** [comment]
Sorry, that didn't post as code.  Actually, the whole thing should be:


`uint8_t digitalInputBytes = 0;
uint8_t digitalOutputBytes = 0;
uint8_t numberOfSlices = 0;

void setup()
{

Serial.begin(115200);
while (!Serial) {}// wait for serial port to connect.

numberOfSlices = P1.init();

for (uint8_t slotIndex = 0; slotIndex < numberOfSlices; slotIndex++) {
moduleProps slotProps = P1.readSlotProps(slotIndex);

    digitalInputBytes += (uint8_t)slotProps.diBytes;
    digitalOutputBytes += (uint8_t)slotProps.doBytes;
}

Serial.print("Digital Input Bytes: "); Serial.println(digitalInputBytes);
Serial.print("Digital Output Bytes: "); Serial.println(digitalOutputBytes);
}

void loop()
{
if (millis() - checkInputsTimer > 10UL)
    {
        P1.readBlockData((char*)dataInputArray, (uint16_t)digitalInputBytes, 0, DISCRETE_IN_BLOCK);
        P1.readBlockData((char*)dataOutputArray, (uint16_t)digitalOutputBytes, 0, DISCRETE_OUT_BLOCK);
        checkInputsTimer = millis();
        for (uint8_t inputBlockIndex = 0; inputBlockIndex < digitalInputBytes; inputBlockIndex++)
        {
            if (dataInputArray[inputBlockIndex] != dataInputArray_old[inputBlockIndex])
            {
                for (uint8_t bitIndex = 0; bitIndex < 8; bitIndex++)
                {
                    if (bitRead(dataInputArray[inputBlockIndex], bitIndex) != bitRead(dataInputArray_old[inputBlockIndex], bitIndex))
                    {
                       // If input change is detected, do something. 
                    }
                }
                dataInputArray_old[inputBlockIndex] = dataInputArray[inputBlockIndex];
            }
        }
    }
}
`


I needed this because I have to poll if an input has changed.  Ideally, if there were an interrupt or some other method to indicated this change, this might not be needed.  

In addition, for our use case I might have anywhere from 1 to 15 modules attached to the P1AM, and while I could scan through the entire block read array, this is slightly more efficient.

**Comment by bbbowden** [comment]
I'm in the process of doing this the correct way and adding an example to the examples directory.  I'll then add to this pull request (or create a new pull request) to add that example.

**Comment by bbbowden** [comment]
I've added an example in my fork but can't seem to get it to show up in this pull request.  Github is also not allowing me to create a new pull request.  Not sure how to proceed at this point.

**Comment by bbbowden** [comment]
Looks like Github fixed their issue and now the pull request has been updated.

Why I did this:

What I am doing is using the P1AM-100 as an MQTT client to publish inputs and subscribe to outputs. Now that I can see what the properties of the modules are a runtime, I can create one codebase that will allow for connection of modules in any order and set up the MQTT client for what it finds.  Makes the platform very flexible.

**Comment by AdamCummick** [comment]
@bbbowden I can see the commits now. 
 
Looking at the readSlotProps function again I have a couple requests. 
1. Change it to receive a 1-indexed slot value instead of zero to match other library functions
2. Add an [early return](https://github.com/facts-engineering/P1AM/blob/19f81e017282f119dfe1fffdaa16aed3f2953c59/src/P1AM.cpp#L300) in the case where slot is not between 1 and 15


Below are my tweaks to your example. Let me know if you have any further suggestions.

```cpp
/*
  Example: Slot Properties
  This example shows how to access the module properties at a given slot. 
  You can then use the module properties in your code without needing to know
  what is in the slot at compile time.  This example uses readBlockData to efficiently
  scan through the inputs for changes.

  This example works with all P1000 Series:
   - Discrete input modules such as P1-08SIM, P1-08ND3, P1-08NA, etc
   - Discrete combo modules such as P1-15CDD1, P1-15CDD2, P1-16CDR, etc. 

  This example will detect the change of any input and then print the byte, bit, and value.
   _____  _____  _____
  |  P  ||  S  ||  S  |
  |  1  ||  L  ||  L  |
  |  A  ||  O  ||  O  |
  |  M  ||  T  ||  T  |
  |  -  ||     ||     |
  |  1  ||  0  ||  0  |
  |  0  ||  1  ||  2  |
  |  0  ||     ||     | etc...
   ¯¯¯¯¯  ¯¯¯¯¯  ¯¯¯¯¯
  Written by Brett Bowden
  Licensed under the MIT license.
*/


#include <P1AM.h>

uint8_t digitalInputBytes = 0;
uint8_t digitalOutputBytes = 0;
uint8_t analogInputBytes = 0;
uint8_t analogOutputBytes = 0;

uint8_t dataInputArray[30] = {0};
uint8_t dataInputArray_old[30] = {0};

uint32_t checkInputsTimer = 0;

void setup(){

  Serial.begin(115200);
  while (!Serial) {}// wait for serial port to connect.

  uint8_t numberOfModules = 0;
  while(numberOfModules == 0) {
    numberOfModules = P1.init();
  }
  
  for (uint8_t slotIndex = 1; slotIndex <= numberOfModules; slotIndex++) {
    moduleProps slotProps = P1.readSlotProps(slotIndex);
    Serial.print("Slot: "); Serial.print(slotIndex); Serial.print(" Module: "); Serial.println(slotProps.moduleName);
    Serial.print("Digital Input Bytes: ");  Serial.println(slotProps.diBytes, DEC);
    Serial.print("Digital Output Bytes: "); Serial.println(slotProps.doBytes, DEC);
    Serial.print("Analog Input Bytes: ");   Serial.println(slotProps.aiBytes, DEC);
    Serial.print("Analog Output Bytes: ");  Serial.println(slotProps.aoBytes, DEC);
    Serial.println();

    digitalInputBytes  += (uint8_t)slotProps.diBytes;
    digitalOutputBytes += (uint8_t)slotProps.doBytes;
    analogInputBytes   += (uint8_t)slotProps.aiBytes;
    analogOutputBytes  += (uint8_t)slotProps.aoBytes;
  }

  Serial.print("Total Digital Input Bytes: ");  Serial.println(digitalInputBytes);
  Serial.print("Total Digital Output Bytes: "); Serial.println(digitalOutputBytes);
  Serial.print("Total Analog Input Bytes: ");   Serial.println(analogInputBytes);
  Serial.print("Total Analog Output Bytes: ");  Serial.println(analogOutputBytes);  

  P1.readBlockData((char*)dataInputArray, (uint16_t)digitalInputBytes, 0, DISCRETE_IN_BLOCK); // Read all inputs
  memcpy(dataInputArray_old, dataInputArray, sizeof(dataInputArray)); // Initialize with current readings
  
}

void loop(){
  if (millis() - checkInputsTimer > 10UL) { // Check inputs every 10ms
    P1.readBlockData((char*)dataInputArray, (uint16_t)digitalInputBytes, 0, DISCRETE_IN_BLOCK); // Read all inputs
    checkInputsTimer = millis();
    
    for (uint8_t i = 0; i < digitalInputBytes; i++) {
      if (dataInputArray[i] != dataInputArray_old[i]) {
        for (uint8_t bitIndex = 0; bitIndex < 8; bitIndex++) {
          if (bitRead(dataInputArray[i], bitIndex) != bitRead(dataInputArray_old[i], bitIndex)) {
            Serial.print("DI Byte: "); Serial.print(i); 
            Serial.print(" Bit: "); Serial.print(bitIndex); 
            Serial.print(" Changed to: "); Serial.println(bitRead(dataInputArray[i], bitIndex));
          }
        }
        dataInputArray_old[i] = dataInputArray[i];
      }
    }
  }
}



```

**Comment by bbbowden** [comment]
Added the slot indexing and early return.  And just copied your example, it was way better.

**Comment by bbbowden** [comment]
Moved slotProperties example as requested.

**Review by AdamCummick — APPROVED** [review]

**Pull request merged**
